/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesSpaceKeyRouteImport } from './routes/spaces/$spaceKey'
import { Route as SpacesSpaceKeyPagesRouteImport } from './routes/spaces/$spaceKey/pages'
import { Route as SpacesSpaceKeyPagesPageIdRouteImport } from './routes/spaces/$spaceKey/pages/$pageId'

const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceKeyRoute = SpacesSpaceKeyRouteImport.update({
  id: '/$spaceKey',
  path: '/$spaceKey',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesSpaceKeyPagesRoute = SpacesSpaceKeyPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => SpacesSpaceKeyRoute,
} as any)
const SpacesSpaceKeyPagesPageIdRoute =
  SpacesSpaceKeyPagesPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => SpacesSpaceKeyPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceKey': typeof SpacesSpaceKeyRouteWithChildren
  '/spaces/$spaceKey/pages': typeof SpacesSpaceKeyPagesRouteWithChildren
  '/spaces/$spaceKey/pages/$pageId': typeof SpacesSpaceKeyPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceKey': typeof SpacesSpaceKeyRouteWithChildren
  '/spaces/$spaceKey/pages': typeof SpacesSpaceKeyPagesRouteWithChildren
  '/spaces/$spaceKey/pages/$pageId': typeof SpacesSpaceKeyPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceKey': typeof SpacesSpaceKeyRouteWithChildren
  '/spaces/$spaceKey/pages': typeof SpacesSpaceKeyPagesRouteWithChildren
  '/spaces/$spaceKey/pages/$pageId': typeof SpacesSpaceKeyPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spaces'
    | '/spaces/$spaceKey'
    | '/spaces/$spaceKey/pages'
    | '/spaces/$spaceKey/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/spaces'
    | '/spaces/$spaceKey'
    | '/spaces/$spaceKey/pages'
    | '/spaces/$spaceKey/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/spaces'
    | '/spaces/$spaceKey'
    | '/spaces/$spaceKey/pages'
    | '/spaces/$spaceKey/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpacesRoute: typeof SpacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceKey': {
      id: '/spaces/$spaceKey'
      path: '/$spaceKey'
      fullPath: '/spaces/$spaceKey'
      preLoaderRoute: typeof SpacesSpaceKeyRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/$spaceKey/pages': {
      id: '/spaces/$spaceKey/pages'
      path: '/pages'
      fullPath: '/spaces/$spaceKey/pages'
      preLoaderRoute: typeof SpacesSpaceKeyPagesRouteImport
      parentRoute: typeof SpacesSpaceKeyRoute
    }
    '/spaces/$spaceKey/pages/$pageId': {
      id: '/spaces/$spaceKey/pages/$pageId'
      path: '/$pageId'
      fullPath: '/spaces/$spaceKey/pages/$pageId'
      preLoaderRoute: typeof SpacesSpaceKeyPagesPageIdRouteImport
      parentRoute: typeof SpacesSpaceKeyPagesRoute
    }
  }
}

interface SpacesSpaceKeyPagesRouteChildren {
  SpacesSpaceKeyPagesPageIdRoute: typeof SpacesSpaceKeyPagesPageIdRoute
}

const SpacesSpaceKeyPagesRouteChildren: SpacesSpaceKeyPagesRouteChildren = {
  SpacesSpaceKeyPagesPageIdRoute: SpacesSpaceKeyPagesPageIdRoute,
}

const SpacesSpaceKeyPagesRouteWithChildren =
  SpacesSpaceKeyPagesRoute._addFileChildren(SpacesSpaceKeyPagesRouteChildren)

interface SpacesSpaceKeyRouteChildren {
  SpacesSpaceKeyPagesRoute: typeof SpacesSpaceKeyPagesRouteWithChildren
}

const SpacesSpaceKeyRouteChildren: SpacesSpaceKeyRouteChildren = {
  SpacesSpaceKeyPagesRoute: SpacesSpaceKeyPagesRouteWithChildren,
}

const SpacesSpaceKeyRouteWithChildren = SpacesSpaceKeyRoute._addFileChildren(
  SpacesSpaceKeyRouteChildren,
)

interface SpacesRouteChildren {
  SpacesSpaceKeyRoute: typeof SpacesSpaceKeyRouteWithChildren
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesSpaceKeyRoute: SpacesSpaceKeyRouteWithChildren,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpacesRoute: SpacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
