/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpacesRouteImport } from './routes/spaces'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesSpaceKeyRouteImport } from './routes/spaces/$spaceKey'
import { Route as SpacesSpaceKeyPageIdRouteImport } from './routes/spaces/$spaceKey/$pageId'

const SpacesRoute = SpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceKeyRoute = SpacesSpaceKeyRouteImport.update({
  id: '/$spaceKey',
  path: '/$spaceKey',
  getParentRoute: () => SpacesRoute,
} as any)
const SpacesSpaceKeyPageIdRoute = SpacesSpaceKeyPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => SpacesSpaceKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceKey': typeof SpacesSpaceKeyRouteWithChildren
  '/spaces/$spaceKey/$pageId': typeof SpacesSpaceKeyPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceKey': typeof SpacesSpaceKeyRouteWithChildren
  '/spaces/$spaceKey/$pageId': typeof SpacesSpaceKeyPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spaces': typeof SpacesRouteWithChildren
  '/spaces/$spaceKey': typeof SpacesSpaceKeyRouteWithChildren
  '/spaces/$spaceKey/$pageId': typeof SpacesSpaceKeyPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spaces' | '/spaces/$spaceKey' | '/spaces/$spaceKey/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spaces' | '/spaces/$spaceKey' | '/spaces/$spaceKey/$pageId'
  id:
    | '__root__'
    | '/'
    | '/spaces'
    | '/spaces/$spaceKey'
    | '/spaces/$spaceKey/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpacesRoute: typeof SpacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spaces': {
      id: '/spaces'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceKey': {
      id: '/spaces/$spaceKey'
      path: '/$spaceKey'
      fullPath: '/spaces/$spaceKey'
      preLoaderRoute: typeof SpacesSpaceKeyRouteImport
      parentRoute: typeof SpacesRoute
    }
    '/spaces/$spaceKey/$pageId': {
      id: '/spaces/$spaceKey/$pageId'
      path: '/$pageId'
      fullPath: '/spaces/$spaceKey/$pageId'
      preLoaderRoute: typeof SpacesSpaceKeyPageIdRouteImport
      parentRoute: typeof SpacesSpaceKeyRoute
    }
  }
}

interface SpacesSpaceKeyRouteChildren {
  SpacesSpaceKeyPageIdRoute: typeof SpacesSpaceKeyPageIdRoute
}

const SpacesSpaceKeyRouteChildren: SpacesSpaceKeyRouteChildren = {
  SpacesSpaceKeyPageIdRoute: SpacesSpaceKeyPageIdRoute,
}

const SpacesSpaceKeyRouteWithChildren = SpacesSpaceKeyRoute._addFileChildren(
  SpacesSpaceKeyRouteChildren,
)

interface SpacesRouteChildren {
  SpacesSpaceKeyRoute: typeof SpacesSpaceKeyRouteWithChildren
}

const SpacesRouteChildren: SpacesRouteChildren = {
  SpacesSpaceKeyRoute: SpacesSpaceKeyRouteWithChildren,
}

const SpacesRouteWithChildren =
  SpacesRoute._addFileChildren(SpacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpacesRoute: SpacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
